<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_HIGODIGITALMANUAL2024_close</name>
   <tag></tag>
   <elementGuidId>e4b19d20-f376-40af-b8c9-0e618219054a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outer-container']/div/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5eaeb0bb-8f45-42b0-b7c3-a770b95e8919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>5a780304-573f-49c2-b67b-7e55b2ec46ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outer-container&quot;)/div[@class=&quot;vm--container&quot;]/div[@class=&quot;vm--modal&quot;]/div[@class=&quot;annual-report-modal-container&quot;]/button[@class=&quot;close&quot;]</value>
      <webElementGuid>98cd244d-49be-45df-bbf0-d19f91c2bce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-container']/div/div[2]/div/button</value>
      <webElementGuid>11cd1fb5-40fe-487d-a98e-bbbf360fb7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BACA SELENGKAPNYA'])[1]/preceding::button[1]</value>
      <webElementGuid>13095340-71c3-4ae3-be23-f52bde86c473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>aa713cb7-80ce-4e73-b12d-b9ae4d9aaed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
