<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lokasi Partner</name>
   <tag></tag>
   <elementGuidId>f2e21646-577e-4ea9-ab20-12219c14b6af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='partner-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#partner-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ee7e085-1d23-4f55-afe9-1acbabfe376d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partner-content</value>
      <webElementGuid>bde07f6b-07c0-4f80-83a3-e924cd66cd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>27b0d566-95a4-45a0-b5d9-274096329db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lokasi Partner</value>
      <webElementGuid>db82f25e-70d0-46da-ad67-dc768e2c6f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partner-content&quot;)</value>
      <webElementGuid>ba8868c3-e7d7-4891-b1a4-cfc97432fa97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='partner-content']</value>
      <webElementGuid>77f9cf1a-20ae-493f-8f22-25d16f2fd97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-container']/div[3]</value>
      <webElementGuid>5dc1c5b3-1da0-481d-a5a0-7f70b32d445d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iklan'])[1]/following::div[1]</value>
      <webElementGuid>631a117d-9735-4c66-8a29-a945bce67775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kebutuhanmu'])[1]/following::div[5]</value>
      <webElementGuid>4bd6463a-23c6-4af2-8b91-c5310132a914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::div[1]</value>
      <webElementGuid>3e5eb921-37a5-4fea-8c5d-68bbd315bd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>abfb30ae-fcf2-42a1-a8db-c2707a7c4bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'partner-content' and (text() = 'Lokasi Partner' or . = 'Lokasi Partner')]</value>
      <webElementGuid>6e8a05e9-9158-4c5b-95cb-9c31985eaa27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
