<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pilih Kebutuhanmu_selected</name>
   <tag></tag>
   <elementGuidId>c8e016fc-2d0b-4232-be4d-0294df164825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='iklan-content']/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6193550c-e573-4524-80cf-ecfd6d217507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>f5168146-b272-46ce-a2a2-eba5fe399ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selected&quot;)</value>
      <webElementGuid>6710e5a6-5b7b-4a64-b36b-66860f5f76c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='selected']</value>
      <webElementGuid>b0589bb5-e5f1-4ff1-9a45-43270e9071d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-container']/div</value>
      <webElementGuid>f62a8148-aafd-4f04-b795-9f98d3951c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div</value>
      <webElementGuid>a5f6dcc9-bada-4714-8ad9-d8308d3d0366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'selected']</value>
      <webElementGuid>e7ab8fb5-a6cf-4b06-a848-54108736af25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
