<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Event</name>
   <tag></tag>
   <elementGuidId>ea8a32d0-6a11-43ba-b404-a18594c4606d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='event-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#event-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2de50846-ddca-4976-8a53-03c27f410460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event-content</value>
      <webElementGuid>dcad61a4-d719-4c23-aa9e-2b0e2d1e1352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7c98d282-2076-4783-a1a4-148c10e8f5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Event</value>
      <webElementGuid>7463cf08-da2e-4bc2-abeb-561da85728bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event-content&quot;)</value>
      <webElementGuid>ff488bbd-5090-467b-9ff5-c259e5bed0a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='event-content']</value>
      <webElementGuid>0e7fd53f-da0f-4c61-bbe6-90b92b740a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-container']/div[4]</value>
      <webElementGuid>7dea4e36-f7d7-4e4a-86cd-028153fc2d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi Partner'])[1]/following::div[1]</value>
      <webElementGuid>db6ead19-f637-48e3-9dd4-ca09cce8e37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iklan'])[1]/following::div[2]</value>
      <webElementGuid>bf9b2391-81a9-47d3-ac1c-257867108bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Punya kafe atau resto? Ciptakan strategi pemasaran lewat data analitik'])[1]/preceding::div[1]</value>
      <webElementGuid>14f9ffdd-6c8b-4ac2-807f-cc5c7db8b7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]</value>
      <webElementGuid>55a74ea2-bd95-4a55-8202-1af12e85a8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'event-content' and (text() = 'Event' or . = 'Event')]</value>
      <webElementGuid>10fb78e4-6142-4745-89a7-b0291359403e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
