<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download Full Report_logoHigo</name>
   <tag></tag>
   <elementGuidId>da267b9e-4b4d-4595-a76b-d7d1e6c45e03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='logoHigo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logoHigo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>42b2ad21-2367-49e5-aa8c-5b331b058f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/HIGO Logo-17.bb52baf8.png</value>
      <webElementGuid>4876c32a-ad9d-4043-a0e6-c8f39e04a7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logoHigo</value>
      <webElementGuid>eec99ead-ea10-4cf6-a8fd-b920d90508eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logoHigo&quot;)</value>
      <webElementGuid>7ba8eb64-f304-4e34-813e-9435ada18a7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='logoHigo']</value>
      <webElementGuid>d9395d54-eaad-474e-9caa-8c0c5315f422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-container']/div[2]/div[3]/header/a/img</value>
      <webElementGuid>d3684e1b-da76-4749-98b6-da703cc2b6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>53d58de2-2bac-42ec-b1ce-806b85da2e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/HIGO Logo-17.bb52baf8.png' and @id = 'logoHigo']</value>
      <webElementGuid>1d5918b4-058a-466e-8f27-a80756048a6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
