<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Campaign</name>
   <tag></tag>
   <elementGuidId>bf617500-c5f9-454e-9142-f2324b139df4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='select-content']/button[2]/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>a4242904-3643-4cb1-9fa0-697ca4bef245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Campaign</value>
      <webElementGuid>92d8599d-01b5-4cd4-93a9-8101f4446c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-content&quot;)/button[@class=&quot;pick-cases&quot;]/h4[1]</value>
      <webElementGuid>de88b591-715a-49cb-8e8b-727a5fcbd538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-content']/button[2]/h4</value>
      <webElementGuid>c7b46eaa-e124-4207-8964-2c91b91bf1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchant'])[1]/following::h4[1]</value>
      <webElementGuid>f616a0ee-98ea-4ad3-bc82-101ed7dec4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kisah sukses yang seneng untuk dibagi-bagi'])[1]/following::h4[2]</value>
      <webElementGuid>f751c62d-c725-45e7-81f6-c80e7951ebec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E: info@higo.id'])[1]/preceding::h4[1]</value>
      <webElementGuid>6d1561cd-6a8c-4d60-b582-6a064ed8335b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P: (021) 5806860'])[1]/preceding::h4[1]</value>
      <webElementGuid>c4462be3-dd6d-4cd6-9bd1-f7290f2a8f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/h4</value>
      <webElementGuid>decb5008-40d6-4053-9bb7-11c4744fbe67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Campaign' or . = 'Campaign')]</value>
      <webElementGuid>b19b66e4-a9e4-4007-b89f-2dca7a1eaecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
